# Generated by Django 4.2.11 on 2024-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='customer',
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='phone',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
